default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: predix-rails-starter-app_development

test:
  <<: *default
  database: predix-rails-starter-app_test

production:
  <<: *default
  database: predix-rails-starter-app_production
  username: predix-rails-starter-app
  password: <%= ENV['PREDIX-RAILS-STARTER-APP_DATABASE_PASSWORD'] %>
